version: 0.0
os: linux
files:
  - source: build/
    destination: /var/www/html/AppliedJobsWeb/
hooks:
  ApplicationStop:
    - location:  application_stop.sh
      timeout: 60
      runas: root  
  BeforeInstall:
    - location: before_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location:  application_start.sh
      timeout: 60
      runas: root
