version: 0.2

phases:
  install:
    runtime-versions:
        java: openjdk8
  build:
    commands:
       - mvn -Pregular clean install assembly:single -DskipTests
artifacts:
  files:
     - target/services_pack/*
  discard-paths: yes
cache:
  paths:
     - '/root/.m2/**/*'
