server:
   port: 8761
eureka:
   instance:
      hostname: localhost
   client:
      registerWithEureka: false
      fetchRegistry: false
   server:
      enableSelfPreservation: false
   serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
   security:
      user:
         name: apple
         password: Go0gl3