spring:
 cloud:
  gateway:
   routes:
   - id: person-service
     uri: ${person-service.url}
     predicates:
      - Path=/person/**
     filters:
      - RewritePath=/person/(?<path>.*), /$\{path}
   - id: address-service
     uri: ${address-service.url}
     predicates:
      - Path=/address/**
     filters:
      - RewritePath=/address/(?<path>.*), /$\{path}
server:
 port: 8083
eureka:
 client:
  serviceUrl:
   defaultZone: http://eureka-server:8761/eureka/
