server:
 port: 8086
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
  fetchRegistry: true
  preferIpAddress: true
zuul:
  ignoredServices: '*'
  routes:
    address:
      path: /address/**
      serviceId: address-service
