server:
 port: 8086
eureka:
 instance:
  hostname: localhost
 client:
  serviceUrl:
   defaultZone: http://apple:Go0gl3@localhost:8761/eureka/
  fetchRegistry: true
  preferIpAddress: true
zuul:
  ignoredServices: '*'
  routes:
    address:
      path: /address/**
      serviceId: address-service
    person:
      path: /person/**
      serviceId: person-service
    admin:
      path: /admin/**
      serviceId: admin
