version: '3'
services:
        ndbsql:
                build: mysql
                environment:
                        lower_case_table_names: 1
                        MYSQL_ROOT_PASSWORD: Selvan_21
                        MYSQL_DATABASE: ndb_dev
                        MYSQL_USER: ndb_app
                        MYSQL_PASSWORD: Ndb_test1
                ports:
                        - "3306:3306"
        web:
                build: tomcat
                depends_on:
                        - ndbsql
                environment:
                        - datasource.url=jdbc:mysql://ndbsql:3306/ndb_dev
                        - datasource.username=ndb_app
                        - datasource.password=Ndb_test1
                ports:
                        - "9090:8080"
                links:
                        - ndbsql
