# docker build -t btamilselvan/node:12 .
# docker run -it -v T:\Git_Repository\tamil\tamils\nodejs:/opt/data --name node12 btamilselvan/node:12
From centos:7

RUN yum -y update

RUN curl -sL https://rpm.nodesource.com/setup_12.x | bash -

RUN yum -y install zip nodejs
