spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
        routes:
           - id: address-service
             uri: lb:address-service
             predicates:
                - Path=/address/**
server:
 port: 8083
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/

