version: 0.0
os: linux
files:
  - source: services.war
    destination: /opt/tomcat/webapps/
permissions:
  - object: /opt/tomcat/webapps
    pattern: "services.war"
    owner: tomcat
    group: root
    mode: 644  
    type:
      - file
hooks:
  BeforeInstall:
    - location: code_deploy_stop.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: code_deploy_start.sh
      timeout: 60
      runas: root